# 配置FreeMarker
# 配置模版文件加载的基础路径，多个路径中间用逗号分隔
spring:
   freemarker:
        templateLoaderPath: classpath:/templates/
# 配置模版文件的后缀名
        suffix: .ftl
# 配置模版文件的编码
        charset: utf-8
# 配置模版文件使用缓存
        cache: true
