bootma:
  uploadPath: c:/var/uploaded_files/
server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8088
#    uri-encoding: utf-8
#  context-path: /bootma

#TRACE, DEBUG, INFO, WARN, ERROR
logging:
  level:
    root: info
    cn.maaa: debug

mybatis-plus:
  mapper-locations: mybatis/**/*.xml
  typeAliasesPackage: cn.maaa.system.domain
  global-config:
    #刷新mapper 调试神器
    db-config:
      #是否开启 LIKE 查询，即根据 entity 自动生成的 where 条件中 String 类型字段 是否使用 LIKE，默认不开启
      column-like: true
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_null
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
spring:
# 指定其他配置文件位置
  profiles:
    active: config/freemarker

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml


  datasource:
    dynamic:
      primary: bootma #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        bootma:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/bootma?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        #bootdo:
         # username: root
         # password: root
         # driver-class-name: com.mysql.jdbc.Driver
         # url: jdbc:mysql://127.0.0.1:3307/bootdo?useUnicode=true&characterEncoding=utf8
  redis:
    port: 6379
    host: 127.0.0.1
 #  password:
    database: 1
    timeout: 2000