server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8080
#    uri-encoding: utf-8
#  context-path: /bootma

#TRACE, DEBUG, INFO, WARN, ERROR
logging:
  level:
    root: info
    cn.maaa: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*.xml
  typeAliasesPackage: cn.maaa.system.domain  

# 分页配置
PageInterceptor:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql  

spring:
# 指定其他配置文件位置
  profiles:
    active: config/freemarker

  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/bootma?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true